name: navbar_router
description: A flutter package to build advanced bottomnavbar with minimal code and hassle

version: 0.5.4
homepage: https://github.com/maheshmnj/navbar_router
repository: https://github.com/maheshmnj/navbar_router
issue_tracker: https://github.com/maheshmnj/navbar_router/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
